In [ ]:
import torch
import torchvision
import torchvision.datasets as datasets
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import h5py

mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=None)
mnist_testset  = datasets.MNIST(root='./data', train=False, download=True, transform=None)


# combine dataset
dataset = mnist_testset # + mnist_trainset

# extract images to np array + labels
samples = []
for el in tqdm(dataset, ncols=120, unit_scale=True):
    img = np.array(el[0])
    lbl = el[1]
    samples.append({"img": img, "lbl": lbl})
    
# STORE: either stacked array (efficient?) or each sample as dict (convenient but inefficient?)

# 1) h5py is perfect for dumping numpy-esque types directly into files!
with h5py.File("testfile.hdf5", "w") as file: 
    dset = file.create_dataset("mydataset", (10, ), dtype="i")
    print(dset[...]) # initialized as empty
    dset[...] = list(range(10))
    print(dset[...])
    dset[...] = np.arange(10)
    print(dset[...])
    
# 2) for complicated samples it might be nice to have one dict per sample with "label", "datax", "datay", "mask", ...
#    but dicts fail for h5yp! 

# 3) so mabye structured array? works!
collection = np.array([
    (1, "alice", 180.5),
    (2, "bob",   176.3),
    (3, "cody",  167.8)
], dtype= [("id", "i4"), ("name", "S10"), ("attr", "f4")])

with h5py.File("testfile.hdf5", "w") as file:
    dset = file.create_dataset("mydataset", data=collection)
    print(dset[...])
    
### so store the mnist files:



100%|█████████████████████████████████████████████████████████████████████████████| 10.0k/10.0k [00:00<00:00, 14.3kit/s]

[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[(1, b'alice', 180.5) (2, b'bob', 176.3) (3, b'cody', 167.8)]


In [ ]:
data = np.array([
    (1, np.random.rand(28, 28)*255),
    (2, np.random.rand(28, 28)*255),
    (3, np.random.rand(28, 28)*255)
], dtype= [("lbl", np.int32), ("img", np.uint8, (28, 28))])


[[240  27 137 170 186 111 220 192 116 220  45  50 162  26 111  13 254 181
   38 196 146  21 128  93 172 147 106 167]
 [217 100  54  62 171 218  15 219   5  82 139 236 139 231   2 253   6 212
  129  47  59 116 139 176 220 212 124 205]
 [ 13 178 254  30 162  78  48 190  59 128 201 189  92 146 246  91 104  38
  194 242 204  45  55 208 187 173 235  81]
 [ 42 184 159 208 171  69 123  55  50  22  72  75   5 147 111 175  93   1
   29 183 125  19  46  58 167 127  59 116]
 [ 86 150  86 207 214 179 228 136 193  72 237 124  13 112 201 221 183  71
   36 144  50   6 150 153 140 170 213 198]
 [145 211  99 164  85 229 242 225 213   0 138  39 168 132 128  92  30  10
    0 247 107 125 189  76 213  37  95  35]
 [241  39 165  67  43 211 229 103 201  63 123 199  27 176  52  72 210 233
  166 225 119 135  77  74  83  41  10  12]
 [245  69 241 216 206  43  23  12 178   6 144 243 111 223 156  55 113  56
  201  27 137 245   2 227 100 121 209  23]
 [197 112  52 138  10 139 201 166 221  83  74  80  73 180  46  3